[[plugins]]
    package = "netlify-plugin-flutter"
    [plugins.inputs]
        channel = "stable"   # or "beta" if you really want that

[build]
    command = "flutter pub get && flutter build web --release --pwa-strategy=offline-first"
    publish = "build/web"

[build.environment]
    PUB_CACHE = "/opt/buildhome/.pub-cache"

# Single Page App routing: deep links -> index.html
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

# Cache policy: keep index fresh, fingerprinted assets long-lived
[[headers]]
    for = "/index.html"
    [headers.values]
        Cache-Control = "no-cache"

[[headers]]
    for = "/*.drill"
    [headers.values]
        Content-Type = "application/vnd.ringdrill+zip"
        Content-Disposition = "attachment"

[[headers]]
    for = "/assets/*"
    [headers.values]
        Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
    for = "/canvaskit/*"
    [headers.values]
        Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
    for = "/main.dart.js"
    [headers.values]
        Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
    for = "/flutter_service_worker.js"
    [headers.values]
        Cache-Control = "no-cache"

[functions]
    directory = "netlify/functions"

[[redirects]]
    from = "/api/drills/upload"
    to = "/.netlify/functions/drills-upload"
    status = 200

[[redirects]]
    from = "/api/drills/head/*"
    to = "/.netlify/functions/drills-head/:splat"
    status = 200

[[redirects]]
    from = "/d/*"
    to = "/.netlify/functions/deep-link/:splat"
    status = 200

[[redirects]]
    from = "/api/market/feed"
    to  = "/.netlify/functions/market-feed"
    status = 200